"""Build review tables from manually assessed sources and preserved Crossref metadata.
No network access. This generates documentation, not experimental results.
"""
import csv, html, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
records={}
for filename in ('crossref_records.json','crossref_additional.json'):
    for item in json.loads((ROOT/filename).read_text()):
        if item['kind']=='doi' and 'metadata' in item:
            records[item['query'].lower()]=item
sources=[]
def paper(id,doi,level,problem,method,modalities,findings,limitations,claim,locator,**kw):
    raw=records[doi.lower()]; m=raw['metadata']
    title=html.unescape(m['title'][0])
    if m.get('subtitle'): title+=': '+m['subtitle'][0]
    s=dict(id=id,doi=doi,title=title,authors='; '.join(a.get('given','')+' '+a.get('family','') for a in m['author']),year=m['published']['date-parts'][0][0],venue=html.unescape('; '.join(m.get('container-title',[]))),volume=m.get('volume',''),issue=m.get('issue',''),pages=m.get('page',''),article=m.get('article-number',''),url='https://doi.org/'+doi,kind='Research publication',peer='Yes (journal/conference publication)',level=level,problem=problem,method=method,modalities=modalities,findings=findings,limitations=limitations,claim=claim,locator=locator,verification=raw.get('resolver',{}),metadata_url=raw['api_url'])
    s.update(kw);sources.append(s)
def doc(id,title,authors,year,venue,url,level,problem,method,claim,locator,**kw):
    s=dict(id=id,title=title,authors=authors,year=year,venue=venue,url=url,doi='',volume='',issue='',pages='',article='',kind='Standard / specification',peer='Not a peer-reviewed research paper',level=level,problem=problem,method=method,modalities='Application-dependent',findings=claim,limitations='Specification defines functionality; not evidence of AMP effectiveness.',claim=claim,locator=locator,verification={},metadata_url=url)
    s.update(kw);sources.append(s)

paper('P01','10.5772/60416','Full text','Remote tactile communication','PARLOMA: depth sensing, networked ROS components and robotic hand','Manual alphabet / robotic tactile hand','Demonstrates remote reproduction of recognized hand shapes.','Restricted hand-shape vocabulary; not general sign-language translation.','Remote assistive communication and hardware abstraction precede AMP.','Architecture and experimental sections',year=2015,article='57',remote='Yes',cross='Yes',bidir='Proposed two-endpoint architecture; demonstration narrower',human='Yes; limited tactile evaluation',cap='Hardware abstraction; not negotiated user profile')
paper('P02','10.1016/j.ifacol.2016.11.145','Abstract only','Remote assistance to visually impaired users','Publish-subscribe assistance architecture','Images/video/location and returned assistance messages','Uses MQTT to connect assistance consumers and providers.','Assessment based on abstract only; detailed delivery lifecycle not verified.','MQTT-based assistive routing is established.','Publisher abstract',remote='Yes',cross='Partial; assistance information transformation',bidir='Request and response',human='Not verified')
paper('P03','10.7160/eriesj.2024.170206','Full text','Braille–speech communication','Bidirectional prototype with tactile output and speech processing','Braille / speech','Demonstrates conversion and prototype trials.','No Deafblind participants: sighted/hearing trials and simulated impairment. Alternating use and surface contact constrain interaction.','Bidirectional Braille–speech conversion is prior art; target-user effectiveness is not demonstrated here.','Methods, two experiments, discussion on recruitment and surface contact',remote='Not established',cross='Yes',bidir='Yes',human='Yes; surrogate evaluation, not Deafblind users')
paper('P04','10.1145/2998181.2998215','Full text','Autonomy and partner assistance in gaze AAC','AACrobat: gaze device and mobile companion linked through cloud data','Gaze / text / speech','Supports user-controlled partner collaboration and visibility into communication state.','Studied primarily co-located; distributed implementation does not establish remote conversational effectiveness.','AAC already includes distributed heterogeneous devices, preferences and conversation state.','System design, study and discussion',remote='Distributed architecture; co-located study',cap='User controls; no general capability handshake verified',cross='Yes',bidir='Partner contribution supported',presentation='Typing/speaking status; not durable render checkpoints',human='Yes')
paper('P05','10.1109/HAPTICS52432.2022.9765570','Full text','Nonvisual and nonauditory communication','MIO Android vibration interface','Morse-like touch input / vibration output','Explores customizable local communication with Deafblind users.','Remote networked protocol not evaluated; usability varies. Replay requests do not establish automatic crash recovery.','Accessible pacing, customization and replay needs have assistive precedents.','Author manuscript: design, usability study and discussion',human='Yes; Deafblind users',cross='Yes',bidir='Local input/output',presentation='User playback controls; not delivery lifecycle',url='https://doi.org/10.1109/HAPTICS52432.2022.9765570',author_url='https://arxiv.org/abs/2205.04802')
paper('P06','10.1016/j.intcom.2012.06.003','Abstract only','Communication access for people with intellectual disabilities','SymbolChat customizable picture messaging','Pictures and configurable input/output','Describes remote messaging adapted to individual needs.','Assessment based on abstract only; wire protocol and recovery not verified.','Remote accessible messaging and interface adaptation predate AMP.','Publisher abstract',remote='Yes',cap='Interface adaptability; negotiation unclear',cross='Partial; representation adaptation',bidir='Messaging',human='Yes; field study reported')
paper('P07','10.3233/TAD-190254','Full text','Benefits and barriers of remote communication','Qualitative study of support persons','Multiple remote communication technologies','Finds social and practical support needs alongside technology barriers.','Support-person accounts are proxy evidence, not protocol benchmarks.','Communication success depends on support and access conditions.','Methods, findings and discussion',remote='Study context',human='Yes; support persons')
paper('P08','10.3389/fcomm.2023.1180257','Abstract only','AAC and digital participation','Conceptual discussion','AAC / digital media','Connects communication access to digital participation.','Assessment based on abstract only; not an evaluated new protocol.','AAC participation motivates requirements beyond device connection.','Publisher abstract',article='1180257')
paper('P09','10.1145/3613904.3641930','Full text','Ability-diverse collaboration research','Systematic literature review using an ability-based lens','Various collaborative modalities','Synthesizes how abilities and collaboration are represented in HCI.','Its reviewed corpus is not the search corpus of this dossier.','Mixed-ability collaboration is an established research field.','Review method, synthesis and discussion',human='Secondary synthesis',article='961')
paper('P10','10.1145/3772318.3790419','Full text','Accessibility practices in virtual mixed-ability teams','Qualitative interview study','Remote collaboration tools','Examines how accessibility practices affect teamwork.','Qualitative contextual evidence, not controlled transport evaluation.','User agency and team practices must inform AMP preference controls.','Publisher full-text methods and findings',human='Yes',remote='Yes; study context',article='161')
paper('P11','10.1145/3772318.3790872','Abstract only','Information access in mixed-visual-ability teams','Study of accessibility-driven information transformations','Multiple information representations','Examines transformation work within collaborative teams.','Assessment based on abstract only; no protocol performance inferred.','Cross-modal conversion can entail human work and access tradeoffs.','Publisher abstract',human='Yes; study reported')
paper('P12','10.1145/3800645.3813075','Abstract only','Conflicting access needs in mixed-ability communication','Interviews and field observations in a nonprofit','Organizational communication technologies','Shows that conflicting access needs involve social roles, norms and accountability.','Assessment based on abstract only; not a protocol comparison. Author manuscript and published DOI identify the same work.','Fallback selection cannot assume one universally preferred modality.','Author manuscript abstract and publication header',human='Yes; qualitative study',author_url='https://arxiv.org/abs/2605.10085')
paper('P13','10.3233/AIS-200578','Full text','Interoperability across IoT platforms','INTER-IoT applied to CasAware','IoT events / semantic data','Combines platform bridges with semantic mediation in an assisted-living case.','Assisted-living integration is not person-to-person accessible presentation.','IoT syntactic and semantic interoperability are prior art.','Architecture and CasAware integration sections',cap='Platform/service integration',cross='Semantic data mediation',remote='Distributed platforms')
paper('P14','10.1002/ett.4544','Abstract only','IoT service discovery and composition','Semantic middleware for description, discovery, selection and composition','IoT services','Describes context-aware semantic service orchestration.','Assessment based on abstract only; accessible output lifecycle not verified.','Semantic discovery and composition are not AMP novelty.','Crossref publisher-deposited abstract',article='e4544',cap='Yes; service discovery',cross='Semantic service composition')
paper('P15','10.3233/AIS-160370','Full text','Flexible and personalized user interfaces','Comparative analysis including URC and GPII','Pluggable interfaces / personal preferences','Describes reusable interface and preference infrastructure.','Comparison of frameworks; not AMP-style conversational recovery experiments.','Device-independent interfaces and preference infrastructure are established.','Relevant framework sections, especially section 4.2.3',cap='Yes; framework descriptions')
paper('P16','10.3390/s24165199','Abstract only','Distribution of multimodal applications at the edge','Multilayer hardware/software platform','Conversational multimodal interfaces','Describes edge deployment and remote management, including assisted-living demonstration.','Assessment based on abstract only; human evaluation and reliability guarantees not verified.','Assistive edge multimodal architecture is prior art.','Publisher-deposited abstract',pages='',article='5199',cross='Multimodal application support',remote='Remote management; peer conversation unclear')
paper('P17','10.1016/j.future.2024.05.026','Abstract only','Heterogeneous edge–cloud application development','CLAID cross-platform middleware','Sensor / AI data','Supports integration across platforms and distributed computation.','Assessment based on abstract only; digital biomarker focus, not accessible conversation.','Edge distribution and platform bridging are implementation foundations.','Publisher abstract',remote='Yes; distributed computation')
# P18 deliberately excluded: only metadata was inspected; do not infer an algorithm from its title.
paper('P19','10.1007/978-3-319-94277-3_33','Abstract only','Remote Deafblind communication','Cloud robotics with tracking and robotic output','Tracked movement / tactile robotic output','Extends a cloud-robotics direction for remote communication.','Assessment based on abstract only; related to PARLOMA, not independent replication.','Cloud-based remote tactile communication precedes AMP.','Springer chapter abstract',volume='10896',remote='Yes',cross='Yes',cap='Not verified')
paper('P20','10.1111/dmcn.15387','Abstract only','Remote intervention for AAC users','Systematic review of teleintervention','AAC / videocommunication','Reviews delivery of AAC intervention at a distance.','Assessment based on abstract only; intervention delivery differs from peer messaging interoperability.','Remote AAC literature is relevant but not automatically equivalent to an assistive protocol.','Publisher abstract',year=2023,metadata_note='Online 2022; final volume 65 issue 2 (2023).',human='Secondary synthesis')
paper('P21','10.36253/form-10189','Abstract only','Remote educational participation with AAC','Assistive/AAC educational case discussion','Eye-gaze / AAC / remote classroom','Discusses access through assistive technologies during pandemic restrictions.','Assessment based on abstract only; no new transport or recovery contract.','Gaze-based remote participation is not an unexplored application.','Official journal abstract')
paper('P22','10.24251/HICSS.2022.259','Abstract only','Communication and robot interaction for Deafblind users','Motion-tracking data glove using an extended Malossi approach','Glove / tactile communication / robot interaction','Describes a glove supporting communication and interaction.','Assessment based on abstract only; no detailed evaluation result inferred. Author names match Crossref and the official AIS proceedings listing.','Glove-mediated remote assistive communication is relevant prior art.','Institutional abstract and Crossref proceedings record',remote='Remote messaging described',cross='Yes; glove communication representation',metadata_note='Deposited spelling retained; official AIS proceedings listing agrees. Institutional records may use alternate name order.',author_url='https://aisel.aisnet.org/hicss-55/da/social_robots/5/')
doc('P23','Lightweight Asynchronous Snapshots for Distributed Dataflows','Paris Carbone; Gyula Fóra; Stephan Ewen; Seif Haridi; Kostas Tzoumas',2015,'arXiv:1506.08603 — PREPRINT','https://arxiv.org/abs/1506.08603','Full text','Fault tolerance for stateful dataflows','Asynchronous Barrier Snapshotting on Apache Flink','Checkpoint recovery of computation is established; physical presentation is a different boundary.','Author manuscript abstract, algorithm context and evaluation section',kind='Preprint',peer='No peer-reviewed version verified',modalities='Data streams',recovery='Yes; computational state',limitations='Digital operator recovery is not evidence of exactly-once human perception.')
paper('P24','10.1145/2018436.2018443','Abstract only','Meeting flow deadlines in datacenters','D3 deadline-aware network design','Network flows','Investigates deadline-aware resource allocation.','Assessment based on abstract only; datacenter conditions differ from assistive output queues.','Deadline awareness alone is established; AMP needs an application-specific advantage.','Official Microsoft Research abstract',authors='Christo Wilson; Hitesh Ballani; Thomas Karagiannis; Ant Rowstron',metadata_note='Crossref lists Ant Rowtron; corrected to Ant Rowstron using Microsoft Research. First author appears as Christo in Crossref and Christopher on the Microsoft page.',author_url='https://www.microsoft.com/en-us/research/publication/better-never-than-late-meeting-deadlines-in-datacenter-networks-2/')
paper('P25','10.1109/JIOT.2016.2615180','Abstract only','IoT middleware capabilities and challenges','Survey of middleware and enabling technologies','Heterogeneous IoT data','Organizes middleware concerns including integration and adaptation.','Assessment based on abstract only. Crossref early-access metadata has a conflicting author name and provisional pages.','IoT middleware is a mature comparison domain for AMP.','Official CSIRO publication record and abstract',year=2017,volume='4',issue='1',pages='1-20',authors='Anne H. H. Ngu; Mario Gutierrez; Vangelis Metsis; Surya Nepal; Quan Z. Sheng',metadata_note='Use CSIRO-authoritative final record; Crossref says Michael Z. Sheng, 2016 and pages 1-1.',author_url='https://publications.csiro.au/publications/publication/PIcsiro%3AEP164932')
doc('P26','What are Multimodalities Made of? Modeling Output in a Multimodal Dialogue System','Christian Elting',2002,'AAAI Technical Report WS-02-08','https://cdn.aaai.org/Workshops/2002/WS-02-08/WS02-08-006.pdf','Full text','Adaptive coordination of multimodal output','EMBASSI output modeling and planning','Multimodal output systems already used acknowledgments after completed presentation.','Output planning and presentation-coordination discussion',kind='Workshop paper',peer='Workshop publication; review procedure not verified',modalities='Multimodal output',cap='Yes; output capabilities/context',cross='Yes; output planning',presentation='Yes; completed presentation',ack='Yes; presentation completion',limitations='Not evidence of durable cross-device partial-presentation recovery in assistive conversation.')

paper('P27','10.1080/10400435.2024.2369547','Abstract only','Intelligibility of device-mediated tactile fingerspelling','HaptiComm versus human-articulated tactile fingerspelling','Australian Deafblind tactile fingerspelling','Device-mediated letters were harder to decipher than human-articulated letters, with differences by tactile site.','Assessment based on abstract only; participant access characteristics and detailed methods not verified.','Renderer actuation and intelligibility must be evaluated separately.','Publisher abstract and Crossref metadata',human='Yes; participant study reported',remote='Not established',author_url='https://researchportal.tuni.fi/en/publications/mediated-and-non-mediated-tactile-fingerspelling-a-comparative-st/',metadata_note='Online publication 2024; later issue assignment not verified.')

doc('S01','Multimodal Architecture and Interfaces','W3C; Jim Barnett (editor)',2012,'W3C Recommendation, 25 October 2012','https://www.w3.org/TR/2012/REC-mmi-arch-20121025/','Full text','Interoperation of modality components','Interaction manager and modality-component lifecycle','Distributed modality components and start/done/pause/resume lifecycle are established.','Section 6 lifecycle events; Appendix F transport binding',remote='Yes; distributed components',cap='Architecture extensibility; profile negotiation unspecified',cross='Framework support',bidir='Bidirectional component events',presentation='Yes; component lifecycle',ack='Yes; lifecycle responses')
doc('S02','Multimodal Interaction Framework','James A. Larson; T. V. Raman; Dave Raggett (editors)',2003,'W3C Note, 6 May 2003','https://www.w3.org/TR/mmi-framework/','Full text','General multimodal interaction organization','Recognition, interpretation, generation, presentation and session functions','Modality separation, user/context adaptation and session concepts predate AMP.','Sections 3, 4, 7 and 8',cross='Yes; framework',cap='Yes; device/context characteristics',presentation='Presentation component')
doc('S03','EMMA: Extensible MultiModal Annotation markup language','Michael Johnston (editor); W3C',2009,'W3C Recommendation, 10 February 2009','https://www.w3.org/TR/emma/','Full text','Exchange of multimodal interpretation annotations','XML annotations including confidence and timing','Intermediate interpretation exchange is established; EMMA is not a universal meaning-preserving translator.','Introduction and annotation/interpretation sections',cross='Interpretation representation')
doc('S04','Web of Things (WoT) Thing Description 1.1','Sebastian Kaebisch; Michael McCool; Ege Korkan (editors)',2023,'W3C Recommendation, 5 December 2023','https://www.w3.org/TR/wot-thing-description11/','Full text','Machine-readable descriptions of Things','Properties, actions, events, data schemas and security descriptions','Device/service description has an existing standard foundation.','Information model and interaction affordances',cap='Yes; device/service descriptions')
doc('S05','Web of Things (WoT) Discovery','Andrea Cimmino; Michael McCool; Farshid Tavakolizadeh; Kunihiko Toumura (editors)',2023,'W3C Recommendation, 5 December 2023','https://www.w3.org/TR/wot-discovery/','Full text','Discovering Things and their descriptions','Introduction and exploration mechanisms','Discovery infrastructure should be reused or compared, not renamed as AMP novelty.','Sections on introduction, exploration and directories',cap='Yes')
doc('S06','MQTT Version 5.0','Andrew Banks; Ed Briggs; Ken Borgendale; Rahul Gupta (editors)',2019,'OASIS Standard, 7 March 2019','https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html','Full text','Publish-subscribe transport','QoS, sessions, expiry and receive limits','MQTT acknowledgment concerns protocol delivery, not proof of accessible presentation.','QoS section 4; message/session expiry and Receive Maximum properties',remote='Yes',ack='Protocol ACK; not presentation ACK',recovery='Session state / retransmission',flow='Receive Maximum limits in-flight QoS packets')
doc('S07','Advanced Message Queuing Protocol (AMQP) Version 1.0','OASIS',2012,'OASIS Standard, 29 October 2012','https://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-complete-v1.0-os.pdf','Full text','Reliable asynchronous messaging','Link credit, settlement, delivery states and link recovery','Receiver credit and partial-transfer resume are prior art; transfer offsets do not establish tactile progress.','Part 2 transport: flow/link credit; Part 3 messaging: 3.4.1 Received',remote='Yes',ack='Delivery state / settlement',flow='Yes; receiver link credit',recovery='Yes; transfer/link state')
doc('S08','Reactive Streams for the JVM, version 1.0.4','Reactive Streams initiative',2022,'Project specification, released 26 May 2022','https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md','Full text','Preventing fast producers overwhelming slow consumers','Asynchronous demand through Subscription.request(n)','Receiver-demand backpressure is established; specification does not define assistive meaning.','Publisher rule 1; Subscriber rule 1; Subscription rules',flow='Yes; demand-based backpressure')
doc('S09','XEP-0333: Displayed Markers, version 1.0.0','Spencer MacDonald; Daniel Gultsch',2024,'XMPP Standards Foundation, 17 April 2024','https://xmpp.org/extensions/attic/xep-0333-1.0.0.html','Full text','Reporting displayed message position','Cumulative displayed markers','Displayed state differs from receipt; the specification also requires accessible marker representations and privacy controls.','Displayed semantics; sections 6, 8 and 11',presentation='Yes; displayed marker, not verified comprehension',ack='Yes; displayed position')
doc('S10','XEP-0198: Stream Management, version 1.6.3','Justin Karneges; Peter Saint-Andre; Joe Hildebrand; Fabio Forno; Dave Cridland; Matthew Wild; Thilo Molitor',2025,'XMPP Standards Foundation, 28 July 2025','https://xmpp.org/extensions/xep-0198.html','Full text','Stanza acknowledgments and stream continuity','Handled-stanza counters and stream resumption','Session resumption and transport/application boundary management precede AMP.','Acknowledgments and resumption sections',ack='Handled stanza; not human display',recovery='Yes; stream resumption',metadata_note='Version 1.6.3 dated 2025-07-28 verified in official document header.')
doc('S11','Bundle Protocol Version 7 (RFC 9171)','S. Burleigh; K. Fall; E. Birrane III',2022,'IETF Standards Track, January 2022','https://www.rfc-editor.org/rfc/rfc9171.html','Full text','Communication under disruption','Bundles, lifetime, fragmentation and status reports','Intermittency, expiry and durable forwarding are established; presentation needs an additional contract.','Bundle fields, lifetime, fragmentation and status reporting',remote='Yes',recovery='Yes; disruption-tolerant forwarding')
doc('S12','Framework for Real-Time Text over IP Using the Session Initiation Protocol (SIP) (RFC 5194)','A. van Wijk; G. Gybels (editors)',2008,'IETF Informational, June 2008','https://www.rfc-editor.org/rfc/rfc5194.html','Full text','Accessible real-time text communication','SIP-based text/multimedia and relay framework','Accessible remote multimedia and relay architectures are prior art.','Framework and accessibility/relay discussion',remote='Yes',cross='Relay support',bidir='Yes')
doc('S13','T.140 Real-Time Text Conversation over WebRTC Data Channels (RFC 8865)','Christer Holmberg; Gunnar Hellström',2021,'IETF Standards Track, January 2021','https://www.rfc-editor.org/rfc/rfc8865.html','Full text','Real-time conversational text over WebRTC','T.140 data channels and SDP negotiation','Receiver maximum character rate can be negotiated and updated; overflow handling is explicit.','Section 4.2.1 character-rate and overflow rules',remote='Yes',cap='Yes; channel/rate parameters',bidir='Yes',flow='Yes; receiver maximum character rate')
doc('S14','Negotiating Human Language in Real-Time Communications (RFC 8373)','Randall Gellens',2018,'IETF Standards Track, May 2018','https://www.rfc-editor.org/rfc/rfc8373.html','Full text','Language needs and preferences in sessions','SDP language negotiation per medium and direction','Language preferences and directional negotiation are established; language-based routing and UI are outside this RFC.','Scope and section 5',cap='Yes; language/media preferences')
doc('S15','Transmission Control Protocol (TCP) (RFC 9293)','W. Eddy (editor)',2022,'IETF STD 7, August 2022','https://www.rfc-editor.org/rfc/rfc9293.html','Full text','Reliable ordered byte streams','Acknowledgment, retransmission and receiver window','Receiver window flow control is established and operates below accessible presentation.','Receiver window and flow-control specification',flow='Yes; byte window',ack='Byte acknowledgment')
doc('S16','Web Content Accessibility Guidelines (WCAG) 2.2','Alastair Campbell; Chuck Adams; Rachael Bradley Montgomery; Michael Cooper; Andrew Kirkpatrick (editors)',2024,'W3C Recommendation, 12 December 2024 revision','https://www.w3.org/TR/2024/REC-WCAG22-20241212/','Full text','Web content accessibility','Success criteria including timing and interaction controls','Timing and control requirements inform interfaces; WCAG is not a complete assistive hardware or protocol standard.','Timing Adjustable and Pause, Stop, Hide criteria',metadata_note='WCAG 2.2 first published in 2023; this citation uses the fixed 2024 revision.')
doc('S17','ISO/IEC 24752-1:2014 — Universal remote console — Part 1: General framework','ISO/IEC',2014,'International Standard; withdrawn November 2021','https://www.iso.org/standard/60821.html','Abstract only','Accessible and replaceable remote user interfaces','Universal remote console framework','Pluggable, device-independent remote interfaces are older prior art.','Official ISO abstract and status',cap='Framework support',limitations='Assessment based on abstract only. Withdrawn edition is historical prior art, not a recommendation to implement a current standard.')
doc('S18','ISO/IEC 24751-2:2008 — Individualized adaptability and accessibility in e-learning, education and training — Part 2: Access for all personal needs and preferences for digital delivery','ISO/IEC',2008,'International Standard','https://www.iso.org/standard/43603.html','Abstract only','Personal accessibility needs and preferences','Functional preference representation for digital delivery','Preference-based access matching is established independently of diagnosis labels.','Official ISO scope/abstract',cap='Personal needs/preferences',limitations='Assessment based on abstract only; education/digital-delivery scope, not an AMP session implementation.')
doc('S19','XEP-0184: Message Delivery Receipts, version 1.4.0','Peter Saint-Andre; Joe Hildebrand',2018,'XMPP Standards Foundation, 2 August 2018','https://xmpp.org/extensions/xep-0184.html','Full text','Client-level message receipt notification','Per-message delivery receipts','Receipt at a recipient client does not imply reading or understanding.','Introduction and receipt semantics',ack='Yes; recipient-client delivery')
doc('S20','XEP-0085: Chat State Notifications, version 2.1','Peter Saint-Andre; Dave Smith',2009,'XMPP Standards Foundation, 23 September 2009','https://xmpp.org/extensions/xep-0085.html','Full text','Communicating conversational activity','Active, composing, paused, inactive and gone states','Conversational state signaling is established.','State model and support discovery',bidir='Chat signaling')

fields=['ID','Paper','Year','Venue','Peer Reviewed?','Research Problem','System / Method','Modalities','Remote?','Capability Awareness?','Cross-Modal?','Bidirectional?','Presentation Tracking?','Flow Control / Pacing?','Recovery?','Human Evaluation?','Major Findings','Limitations','Relevance to AMP','DOI / Official URL','Evidence Level']
def savecsv(name,fields,rows):
    with (ROOT/name).open('w',newline='') as f:
        w=csv.writer(f);w.writerow(fields);w.writerows(rows)
savecsv('CORE_LITERATURE.csv',fields,[[s['id'],s['title'],s['year'],s['venue'],s['peer'],s['problem'],s['method'],s.get('modalities','Application-dependent'),s.get('remote','Not reported / not verified'),s.get('cap','Not reported / not verified'),s.get('cross','Not reported / not verified'),s.get('bidir','Not reported / not verified'),s.get('presentation','Not reported / not verified'),s.get('flow','Not reported / not verified'),s.get('recovery','Not reported / not verified'),s.get('human','Not reported / not applicable'),s['findings'],s['limitations'],s['claim'],s['url'],s['level']] for s in sources])
(ROOT/'SOURCE_ASSESSMENTS.json').write_text(json.dumps(sources,ensure_ascii=False,indent=2))
refs=['# Verified references and access notes','', 'Review cutoff and access date: 15 September 2026. P = research publication, workshop paper or explicitly labeled preprint. S = standards/specifications. P18 is excluded; the numbering gap is intentional. DOI metadata verification does not imply successful publisher full-text access.','']
bib=[];audit=[]
for s in sources:
    details='; '.join(x for x in [str(s['volume'])+('('+str(s['issue'])+')' if s['issue'] else '') if s['volume'] else '', 'pp. '+s['pages'] if s['pages'] else '', 'article '+s['article'] if s['article'] else ''] if x)
    refs += [f"## {s['id']}",'',f"{s['authors']}. **{s['title']}**. *{s['venue']}*, {s['year']}"+(f', {details}' if details else '')+'. '+f"[Official record]({s['url']})."+(f" DOI: {s['doi']}." if s['doi'] else ' DOI not supplied; official URL used.'),'',f"**Type:** {s['kind']}. **Review status:** {s['peer']}. **Evidence:** {s['level']}."+(' Assessment based on abstract only.' if s['level']=='Abstract only' else ''),'',f"**Examined evidence:** {s['locator']}. **Supported use:** {s['claim']}",'',f"**Limit:** {s['limitations']}",'']
    if s.get('author_url'):refs += [f"[Author/institutional version]({s['author_url']}).",'']
    if s.get('metadata_note'):refs += ['**Metadata note:** '+s['metadata_note'],'']
    res=s['verification']; doi_status=('Crossref identity verified; resolver '+str(res.get('status','not recorded'))+' → '+res.get('url','not recorded')) if s['doi'] else 'Not supplied; official source used'
    authors_status='Verified against authoritative record'
    if s['id']=='P22':authors_status='Crossref and official AIS proceedings listing agree; deposited spelling retained'
    if s['id']=='P25':authors_status='CSIRO record used; Crossref discrepancy flagged'
    year_status='Verified'
    audit.append([s['id'],'Verified',authors_status,year_status,'Verified',doi_status,s['level'],s['claim'],s['locator'],s.get('metadata_note','')])
    typ='misc' if not s['doi'] else ('article' if 'journal' in str(records.get(s['doi'].lower(),{}).get('metadata',{}).get('type','')) else 'inproceedings')
    # Braced Unicode authors preserve institutional names and deposited author spelling.
    esc=lambda v:str(v).replace('&',r'\&').replace('%',r'\%').replace('_',r'\_')
    attrs={'title':'{'+esc(s['title'])+'}','author':' and '.join('{'+esc(a.strip())+'}' for a in s['authors'].split(';')),'year':s['year'],'url':s['url'],'note':s['kind']+'; evidence: '+s['level']}
    attrs['journal' if typ=='article' else 'booktitle' if typ=='inproceedings' else 'howpublished']=esc(s['venue'])
    for key, val in [('doi',s['doi']),('volume',s['volume']),('number',s['issue']),('pages',s['pages'])]:
        if val:attrs[key]=val
    bib.append('@'+typ+'{'+s['id']+',\n'+',\n'.join('  '+k+' = {'+str(v)+'}' for k,v in attrs.items())+'\n}')
(ROOT/'REFERENCES.md').write_text('\n'.join(refs))
(ROOT/'references.bib').write_text('\n\n'.join(bib)+'\n')
savecsv('CITATION_AUDIT.csv',['Ref. ID','Title Verified','Authors Verified','Year Verified','Venue Verified','DOI Verified','Full Text?','Used for Which Claim?','Evidence locator','Uncertainty'],audit)

# Conservative feature coding. Unspecified cells mean NOT REPORTED in the examined evidence.
features=['Remote communication','Different user accessibility needs','Heterogeneous devices','Multiple input modalities','Multiple output modalities','Cross-modal transformation','Capability discovery','Preference negotiation','Semantic/intermediate representation','Automatic modality selection','Bidirectional communication','Conversation/session state','Presentation-state tracking','Application ACK','Partial presentation recovery','Duplicate handling','Message expiry','Receiver-rate awareness','Queue/backpressure control','User-approved fallback','Intermittent network recovery','Edge execution','Real physical testbed','Human evaluation']
# Features numbered 1..24 in precisely the order above.
coding={
 'P01':([1,3,6,9,22,23,24],[2,7,11]),
 'P02':([1,3],[2,4,5,6,9,11,23,24]),
 'P03':([3,4,5,6,11,22,23,24],[2,9]),
 'P04':([2,3,4,5,6,9,11,12,22,23,24],[1,8,13,20]),
 'P05':([6,11,22,23,24],[2,3,4,5,8,9,13,18,20]),
 'P06':([1,2,11,24],[3,4,5,6,7,8,9,23]),
 'P13':([1,3,9,23],[6,7,10,22]),
 'P15':([3,7],[1,2,4,5,8,9,10,20,22]),
 'P16':([3,22],[1,2,4,5,6,9,10,11,23]),
 'P19':([1,3,6],[2,7,9,11,22,23,24]),
 'P22':([1,6],[2,3,9,11,22,23,24]),
 'P26':([5,7,9,10,13,14],[1,3,4,6,8,12,18,19,20,23]),
 'S01':([1,3,4,5,11,12,13,14],[6,7,8,9,10,15,18,19,20,21,22]),
 'S07':([1,3,14,17,19,21],[11,12,16,18]),
 'S13':([1,7,11,12,18],[2,3,8,19,21]),
}
rows=[]
for id,(yes,partial) in coding.items():
    assert not set(yes)&set(partial)
    rows.append([id]+['✓' if i in yes else '△' if i in partial else '✗' for i in range(1,25)])
rows.append(['AMP — PROPOSED — NOT PRIOR ART']+['△']*24)
savecsv('FEATURE_MATRIX.csv',['System']+features,rows)
(ROOT/'FEATURE_MATRIX.md').write_text('# Feature matrix\n\n✓ Confirmed in examined evidence; △ Partial / unclear; ✗ Not reported in examined evidence. These are not capability impossibility claims. Specifications show specified functionality, not physical experiments. All AMP cells are △ because they are proposed or owner-reported and lack an evaluated AMP research artifact.\n\nFull 24-column matrix: [FEATURE_MATRIX.csv](FEATURE_MATRIX.csv).\n\nImportant qualifications: P03 human evaluation used surrogate conditions; P04 remote operation was not the evaluated setting; P05 is a local vibration system; P15 is a framework comparison, not one new system; S07 recovery concerns transfer/link state, not physical presentation. Abstract-only rows are deliberately sparse. Read [SOURCE_ASSESSMENTS.json](SOURCE_ASSESSMENTS.json) and [REFERENCES.md](REFERENCES.md) alongside the matrix. Do not sum checkmarks as a novelty score.\n')

logs=json.loads((ROOT/'search_sessions.json').read_text())
for x in logs:
    if x['retained']=='Pending screening':x['retained']='Not recorded per query; see screened corpus and source locators'
logs.extend([dict(id='V13',source='Official venue pages / web open',query='https://shop.elsevier.com/journals/journal-of-network-and-computer-applications/1084-8045 ; https://taccess.acm.org/',date='2026-09-15',inspected='2 URLs attempted',retained='JNCA scope verified; TACCESS unavailable'),dict(id='S08-check',source='Official specification / web open',query='https://www.reactive-streams.org/ ; https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md',date='2026-09-15',inspected='2 URLs inspected',retained='S08')])
for i,raw in enumerate(list(records.values()),1):
    retained=next((s['id'] for s in sources if s['doi'].lower()==raw['query'].lower()),'Excluded P18: metadata-only scheduling lead')
    logs.append(dict(id=f'CR{i:02}',source='Crossref direct API and DOI resolver',query=raw['api_url'],date='2026-09-15',inspected='1 metadata record; resolver attempted',retained=retained))
for i,raw in enumerate(json.loads((ROOT/'crossref_records.json').read_text()),1):
    if raw['kind']=='query':
        logs.append(dict(id=f'CRQ{i:02}',source='Crossref direct API title query; rows=2',query=raw['query'],date='2026-09-15',inspected='Returned candidates inspected; see preserved JSON',retained='Identity candidates only; matched DOI records screened separately'))
for i,q in enumerate(['"Communicating with Humans and Robots" "Doubrowski"','"XEP-0198" "Version" "2025"','"Mediated and non-mediated tactile fingerspelling" abstract','"Mediated and non-mediated tactile fingerspelling" authors'],1):
    logs.append(dict(id=f'FINAL{i}',source='Web discovery followed by authoritative source check',query=q,date='2026-09-15',inspected='Not recorded / unavailable',retained='P22 author check; S10 version check; P27 screening'))
savecsv('SEARCH_LOG.csv',['Search ID','Database/Source','Search Query','Date Searched','Results Inspected','Relevant Studies Retained'],[[x[k] for k in ['id','source','query','date','inspected','retained']] for x in logs])
source_urls={s['id']:s['url'] for s in sources}
for filename in ['REVIEW.md','MANUSCRIPT_RELATED_WORK.md']:
    path=ROOT/filename
    if path.exists():
        text=path.read_text()
        text=re.sub(r'\[((?:[PS]\d{2})(?:, [PS]\d{2})*)\](?!\()',lambda m:', '.join('['+id+']('+source_urls[id]+')' for id in m[1].split(', ')),text)
        path.write_text(text)
print(json.dumps({'sources':len(sources),'research_items':sum(s['id'].startswith('P') for s in sources),'standards':sum(s['id'].startswith('S') for s in sources),'full_text':sum(s['level']=='Full text' for s in sources),'abstract_only':sum(s['level']=='Abstract only' for s in sources),'closest_rows':len(coding),'search_rows':len(logs)},indent=2))
